/*******************************************************************************
 *    sora-editor - the awesome code editor for Android
 *    https://github.com/Rosemoe/sora-editor
 *    Copyright (C) 2020-2025  Rosemoe
 *
 *     This library is free software; you can redistribute it and/or
 *     modify it under the terms of the GNU Lesser General Public
 *     License as published by the Free Software Foundation; either
 *     version 2.1 of the License, or (at your option) any later version.
 *
 *     This library is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *     Lesser General Public License for more details.
 *
 *     You should have received a copy of the GNU Lesser General Public
 *     License along with this library; if not, write to the Free Software
 *     Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
 *     USA
 *
 *     Please contact Rosemoe by email 2073412493@qq.com if you need
 *     additional information or have any questions
 ******************************************************************************/

package io.github.rosemoe.sora.lang.brackets

import android.os.Bundle
import io.github.rosemoe.sora.text.CharPosition
import io.github.rosemoe.sora.text.ContentReference
import io.github.rosemoe.sora.widget.CodeEditor

interface IncrementalBracketsProvider: BracketsProvider {
    /**
     * Called when new text is set in editor by either [CodeEditor.setText]
     * or [CodeEditor.setText]
     *
     * @param content        New text, read-only. Accesses to it are not validated. It is not recommended saving
     * this object for reading. You can make a copy of the text and update it. But for
     * memory saving, you may want to store it.
     * @param extraArguments Arguments set by [CodeEditor.setText]
     */
    fun reset(content: ContentReference, extraArguments: Bundle)

    /**
     * The [ContentReference] set by [.reset] has inserted
     * text with the given position and text.
     *
     * @param start           The insertion start
     * @param end             The insertion end
     * @param insertedContent The content inserted
     */
    fun insert(start: CharPosition, end: CharPosition, insertedContent: CharSequence)

    /**
     * The [ContentReference] set by [.reset] has deleted
     * text with the given position and text.
     *
     * @param start          The deletion start
     * @param end            The deletion end
     * @param deletedContent The text deleted. Generated by [io.github.rosemoe.sora.text.Content] object.
     */
    fun delete(start: CharPosition, end: CharPosition, deletedContent: CharSequence)
}